[project]
name = "binance-historical-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "char>=0.1.2",
    "mpire>=2.10.2",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
